/**
 * Script Properties (secrets + small state) and `config` sheet defaults.
 * Secrets live only in Script Properties (D-04, §13).
 */
const PROP = {
  BOT_TOKEN: 'BOT_TOKEN',           // from BotFather
  OWNER_ID: 'OWNER_ID',             // my Telegram user id
  WEBHOOK_KEY: 'WEBHOOK_KEY',       // ≥ 32 chars, generated by setup()
  SPREADSHEET_ID: 'SPREADSHEET_ID', // created by setup()
  WEBAPP_URL: 'WEBAPP_URL',         // optional override of DEFAULT_WEBAPP_URL
  PAGES_URL: 'PAGES_URL',           // Mini App origin registered in BotFather
  LAST_UPDATE: 'LAST_UPDATE',       // {"id":n,"ts":ms} durable dedupe state
};

const DEFAULT_PAGES_URL = 'https://bekorchiakkaunt1-coder.github.io/Koreys-tili/';
/** Prod deployment (kept stable via update-deployment / Edit → New version). Not a secret. */
const DEFAULT_WEBAPP_URL = 'https://script.google.com/macros/s/AKfycbzX20CH14w-SFPFlQteIsoIbsead6Jv6_EkFdSiBe2uwa5Y_Uxl0q8J45O3hF-DcFE0Fg/exec';

/** Defaults written to the `config` sheet by setup(); the sheet wins afterwards. */
const CONFIG_DEFAULTS = {
  day_start_hour: 5,
  desired_retention: 0.9,
  new_per_day: 12,          // D-22
  max_age_initdata_s: 86400,
  exam_target: '110th PBT · TOPIK I · 2027-01-10',
  exam_date: '2027-01-10',
  params_version: 1,
  vendor_ver: '1',
};

/** @param {string} key @return {string|null} */
function prop_(key) {
  return PropertiesService.getScriptProperties().getProperty(key);
}

/** @param {string} key @param {string} value */
function setProp_(key, value) {
  PropertiesService.getScriptProperties().setProperty(key, String(value));
}

/** @return {string} */
function requireProp_(key) {
  const v = prop_(key);
  if (!v) throw new Error('Script property missing: ' + key);
  return v;
}

/**
 * Reads the `config` sheet as {key: value} merged over CONFIG_DEFAULTS.
 * Cached for 10 min; setup() and config writes clear the cache.
 * @return {Object<string, *>}
 */
function getConfig_() {
  const cache = CacheService.getScriptCache();
  const hit = cache.get('config');
  if (hit) return JSON.parse(hit);
  const cfg = Object.assign({}, CONFIG_DEFAULTS);
  Repo.readAll('config').forEach(function (r) {
    if (r.key) cfg[r.key] = r.value;
  });
  cache.put('config', JSON.stringify(cfg), 600);
  return cfg;
}
